apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: a9m81veb7-java-springboot
  janus-idp.io/tekton: a9m81veb7-java-springboot
  backstage.io/kubernetes-id: a9m81veb7-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a9m81veb7-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
